---
title:
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: Home, CVE.
baseurl: ''
url: https://thxsena.github.io
twitter_username: 
github_username: thxsena
markdown: kramdown
permalink: "/:categories/:title/"
kramdown:
  input: GFM
gems:
- jekyll-sitemap
- jekyll-redirect-from
authors:
  fuzzy:
    display_name:
    twitter:
    web
  verr:
    display_name:
    twitter:
    github:
  f0rki:
    display_name:
    twitter:
    web: 
    github:
  kw:
    twitter:
  skogler:
    display_name: skogler
  creed: 
  kree: 
  sigttou:
    twitter:
  roman: 
  wolvg: 
  jrandom: 
  yrlf:
    twitter:
    github: 
theme: jekyll-theme-hacker
