# Site settings
title: CTF
email: ""
description: "ctfs, write-ups."
baseurl: ""
url: "https://mtps3.github.io"
twitter_username: @pwn0bot1
github_username:  @mtps3
# Build settings
markdown: kramdown
permalink: pretty

kramdown:
    input: GFM

# github gems
# (see https://help.github.com/categories/github-pages-features/ )
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
#  - jekyll-mentions


